[[constraint]]
  name = "gopkg.in/urfave/cli.v1"
  version = "1.20.0"

[[constraint]]
  name = "github.com/google/go-github"

[[constraint]]
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "golang.org/x/net"
